version: 3.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
- x86
clone_depth: 1
install:
- cmd: >-
    cd c:\projects\r3\make\msvc\

    call Make-vs-project.bat
build:
  project: C:\projects\r3\make\msvc\Rebol3.sln
  verbosity: normal