freebsd_instance:
  image_family: freebsd-13-0

task:
  env:
    CIRRUS_CLONE_DEPTH: 1

  install_script:
    - date
    - uname -a
  # WGET is not working on Cirrus FreeBSD VM anymore :-/
  #  - pkg install -y wget
  #  - wget -nv https://github.com/Siskin-framework/Builder/releases/download/0.7.2/Siskin-x64-freebsd.gz
  # Trying to do the same with CURL (if it exists there)
    - curl -L -S https://github.com/Siskin-framework/Builder/releases/download/0.7.2/Siskin-x64-freebsd.gz --output Siskin-x64-freebsd.gz
    - gunzip ./Siskin-x64-freebsd.gz
    - mv ./Siskin-x64-freebsd ./Siskin
    - chmod u+x ./Siskin
    - ./Siskin --version

  matrix:
   - name: Rebol3/Base FreeBSD ARM64
     script:
       - ./Siskin make/rebol3.nest %rebol3-base-freebsd-x64
       - ./build/rebol3-base-freebsd-x64 -v
       - gzip -9 ./build/rebol3-base-freebsd-x64
  
   - name: Rebol3/Core FreeBSD ARM64
     script:
       - ./Siskin make/rebol3.nest %rebol3-core-freebsd-x64
       - ./build/rebol3-core-freebsd-x64 -v
       - gzip -9 ./build/rebol3-core-freebsd-x64

    - name: Rebol3/Bulk FreeBSD ARM64
      script:
        - ./Siskin make/rebol3.nest %rebol3-bulk-freebsd-x64
        - ./build/rebol3-bulk-freebsd-x64 -v
        - ./build/rebol3-bulk-freebsd-x64 -s ./src/tests/run-tests.r3
        - gzip -9 ./build/rebol3-bulk-freebsd-x64

  binaries_artifacts:
   path: "build/*"
