#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

notifications:
    email: false

language: c

compiler:
    - gcc
    - clang

env:
    matrix:
        # Linux x86
        - OS_ID=0.4.4
        # Linux x64
        - OS_ID=0.4.40

before_install:
    - sudo apt-get update

install:
    # gcc-multilib:
    #   For building 32b binaries on a 64b host (not necessary when we build
    #   for 64b).
    # valgrind:
    #   For basic sanity checking of our freshly built binaries.
    # libc6:i386:
    #   For running the 32b bootstrap rebol ("r3-make") on a 64b host.
    # libc6-dbg:i386:
    #   For running valgrind on a 32b subject-under-test on a 64b host.
    - sudo apt-get install -y gcc-multilib valgrind libc6:i386 libc6-dbg:i386

script:
    - cd make/
    - prebuild/r3-make-linux -qs ../src/tools/make-make.r ${OS_ID}
    - make clean prep r3
    - valgrind -v --error-exitcode=42 --track-origins=yes --leak-check=full ./r3 --do run-tests
