name: 'Rebol CI Windows ARM'
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.18.5

    - name: Check installed SDKS
      run: Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows Kits\Installed Roots" | ForEach-Object { $_.GetValue("KitsRoot10") }

    - name: Build 64bit Rebol/Bulk using MSVC
      run: |
        ./siskin make/rebol3.nest --test --msvc rebol3-bulk-windows-arm64
        call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64_arm64
        cd ./msvc
        msbuild "rebol3-bulk-windows-arm64.sln" /p:Configuration=Release /p:Platform="ARM" /p:WindowsTargetPlatformVersion=10.0.22621.0
        MOVE ./msvc/Release-ARM/rebol3-bulk-windows-arm64.exe ./

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-CI-${{github.run_id}}-windows-arm
        path: ./rebol3-*.exe
