name: 'Rebol CI Windows ARM'
on:
  # Triggers the workflow on push or pull request events but only for the arm-win branch
  push:
    branches: [ arm-win ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-11-arm64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.18.5
      with:
        arch: arm64

    - name: Build 64bit Rebol/Bulk using MSVC
      run: |
        ./siskin -V
        ./siskin make/rebol3.nest -o . --msvc rebol3-bulk-windows-arm64


    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-CI-${{github.run_id}}-windows-arm
        path: ./rebol3-*.exe
